version: '3'
services:
  db:
    image: postgres:15.4-alpine3.18
    container_name: rubyapp-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_DB: Budgy_production
      POSTGRES_USER: Budgy
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DB_HOST: db
      DB_NAME:  Budgy_production
      DB_USERNAME: Budgy
      DB_PASSWORD: postgres
    volumes:
      - .:/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres_data: {}